[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["images/**"]

# Optional but recommended
[functions."create-checkout-session"]
  timeout = 10

[functions."verify-session"]
  timeout = 10

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true